-- Vim nargs options
-- 0: No arguments.
-- 1: Exactly one argument.
-- ?: Zero or one argument.
-- *: Any number of arguments (including none).
-- +: At least one argument.
-- -1: Zero or one argument (like ?, explicitly).

vim.api.nvim_create_autocmd('VimLeavePre', {
  callback = function()
    local function clean(path)
      local global_path = path
      if vim.fn.filereadable(global_path) == 0 then
        return
      end
      local file_read = io.open(global_path, 'r')
      if not file_read then
        return
      end
      local content = file_read:read('*a')
      file_read:close()

      local cache_id = string.sub(vim.fn.sha256(OS.project_dir), 1, 16)
      local start_marker = '# --- AUTOMATICALLY GENERATED BY NVIM-PIO - DO NOT EDIT START: ' .. cache_id .. ' ---'
      local end_marker = '# --- AUTOMATICALLY GENERATED BY NVIM-PIO - DO NOT EDIT END: ' .. cache_id .. ' ---'
      -- local start_marker = '# --- NVIM-PIO SESSION START: ' .. cache_id .. ' ---'
      -- local end_marker = '# --- NVIM-PIO SESSION END: ' .. cache_id .. ' ---'

      local start_idx = content:find(start_marker, 1, true)
      local end_idx = content:find(end_marker, 1, true)
      if start_idx and end_idx then
        local actual_end = end_idx + #end_marker
        -- If it encounters Windows CRLF (\r\n), skip both characters cleanly.
        if content:sub(actual_end, actual_end + 1) == '\r\n' then
          actual_end = actual_end + 2
        -- If it encounters Linux/macOS LF (\n), skip the single character.
        elseif content:sub(actual_end, actual_end) == '\n' then
          actual_end = actual_end + 1
        end

        content = content:sub(1, start_idx - 1) .. content:sub(actual_end)
        content = content:gsub('\n\n+$', '\n')
        local file_write = io.open(global_path, 'w')
        if file_write then
          file_write:write(content)
          file_write:close()
        end
      end
    end
    -- local cwdClangd = vim.fs.joinpath(OS.project_dir, '.clangd')
    local pkgClangd = vim.fs.joinpath(_G.metadata.toolchain_root, '.clangd')
    local frmClangd = vim.fs.joinpath(_G.metadata.framework_root, '.clangd')
    -- clean(cwdClangd)
    clean(pkgClangd)
    clean(frmClangd)
  end,
})
-- GARBAGE COLLECTION ENGINE: Wipes the global YAML block completely upon exit
-- local misc = require('nvimpio.utils.misc')
-- vim.api.nvim_create_autocmd('VimLeavePre', {
--   callback = function()
--     local cache_id = require('nvimpio.boilerplate').get_session_cache_id()
--     local start_marker = '# --- NVIM-PIO SESSION START: ' .. cache_id .. ' ---'
--     local end_marker = '# --- NVIM-PIO SESSION END: ' .. cache_id .. ' ---'
--
--     local cwdClangd = OS.clangd_user_file
--     local ok, content = misc.readFile(cwdClangd)
--     if ok and type(content) == string and content ~= '' then
--       local safe_start_pattern = start_marker:gsub('%-', '%%-')
--       local safe_end_pattern = end_marker:gsub('%-', '%%-')
--       content = content:gsub('\n?' .. safe_start_pattern .. '.-' .. safe_end_pattern .. '\n?', '')
--     end
--     if ok and content then
--       misc.writeFile(cwdClangd, content, {})
--     end
--   end,
-- })

-- stylua: ignore start
local upkeep = require('nvimpio.pio.upkeep')
local cmd = vim.api.nvim_create_user_command

-- INFO: Refresh PIO Data
cmd('PioRefreshData', function ()
   _G.isBusy = true
   local pio_refresh = upkeep.pio_refresh
   pio_refresh(function(success)
     if success then do end end
     _G.isBusy = false
   end, 'PIO refresh command: ')
end, {desc = 'Refresh PIO metadata'})


-- INFO: PlatformIO installation
cmd('PioInstall', function()
  local ok_main, main = pcall(require, "nvimpio")
  if not ok_main then return end

  local current_pio_opts = (main.options and main.options.pio) or (main.defaults and main.defaults.pio) or {}
  local raw_runtime_dir = require('nvimpio.core').resolve_user_path(current_pio_opts.pio_runtime_dir)

  if not raw_runtime_dir or raw_runtime_dir == "" then
    raw_runtime_dir = OS.is_win and vim.fs.joinpath(vim.env.USERPROFILE, '.platformio')
      or vim.fs.joinpath(vim.uv.os_homedir(), '.platformio')
  end

  local base_runtime = raw_runtime_dir
  local bin_subfolder = OS.is_win and 'Scripts' or 'bin'
  local target_bin = vim.fs.joinpath(base_runtime, 'penv', bin_subfolder)

  local function install()
    require('nvimpio.pio.ui.pioInstall').pioInstall(base_runtime, function (status)
      if(status) then OS.notify("PIO installed successfully") end
    end)
  end
  local local_pio_executable = vim.fs.joinpath(target_bin, (OS.is_win and 'pio.exe' or 'pio'))
  if vim.fn.executable(local_pio_executable) == 1 then
    if vim.fn.confirm('PlatformIO already Installed, reinstall?', '&Yes\n&No', 1) == 1 then install() end
  else install() end
end, {
  force = true,
  desc = 'Start the PlatformIO guided install wizard',
})


-- INFO: manage gitignore
------------------------------------------------------
cmd('PioGitIgnore', function() require('nvimpio.pio.ui.pioGitIgnore').pioGitIgnore()
  end, { force = true, desc = 'add/remove files/folder to/from gitignore' })

-- -- INFO: List ToggleTerminals
-- ------------------------------------------------------
-- cmd('PioTermList',
--   function()
--     require('nvimpio.pio.ui.pioTermList').pioTermList()
--   end,
--   {
--     force = true,
--     desc = 'Start the PlatformIO Terminals list'
--   }
-- )

------------------------------------------------------

------------------------------------------------------
cmd('Piorun', function(opts) local args = opts.args require('nvimpio.pio.cli').piorun({ args })
end, { nargs = '?', complete = function(_, _, _) return { 'upload', 'uploadfs', 'build', 'clean' } end, })

-- Add this command registry string helper directly to your setup hooks
cmd('Piomon', function(opts) local args = opts.fargs require('nvimpio.pio.cli').piomon(args)
end, {
  nargs = '*',
  complete = function(_, cmd_line)
    local ports = upkeep.get_connected_ports()
    local parts = vim.split(cmd_line, '%s+')
    local BAUD = { '4800', '9600', '57600', '115200' }
    if #parts == 2 then return BAUD end
    if #parts == 3 then return ports end
    return {}
  end,
})

cmd('PioCompileDB', function() require('nvimpio.pio.ui.pioCompileDB').pioCompileDB() end, { desc = "Install PlatformIO Core" })
cmd('PioPickEnv', function() require('nvimpio.pio.ui.activeEnvPicker').select_env_picker() end, { desc = 'Switch [E]nvironment' })
cmd('PioRepair', function() require('nvimpio.pio.ui.pioRepair').pioRepair() end, { desc = "repair PlatformIO Core" })
cmd('PioUpgrade', function() local cmd_table = {'upgrade'} require('nvimpio.pio.cli').piocli(cmd_table) end, {})
cmd('PioSelectPort', function() upkeep.configure_hardware_parameters() end, { force = true })
--INFO: fix paths in compile_commands.json
cmd('PioDbFixPaths', function() upkeep.compile_commandsFix() end, {})
cmd('PioDevList', function() local cmd_table = {'device', 'list'} require('nvimpio.pio.cli').piocli(cmd_table) end, {})
cmd('Piolib', function(opts) local args = vim.split(opts.args, ' ') require('nvimpio.pio.ui.piolib').piolib(args) end, { nargs = '+', })
cmd('Piocli', function(opts) local cmd_table = vim.split(opts.args, ' ') require('nvimpio.pio.cli').piocli(cmd_table) end, { nargs = '*', })
cmd('Piodebug', function() require('nvimpio.pio.cli').piodebug() end, {})

-- stylua: ignore end
