-- function M.get_active__env(from)
--   from = (type(from) == 'string' and from ~= '') and from or 'PIO: '
--
--   -- 1. Locate the configuration using safe, cross-platform Neovim core logic
--   local path = vim.fs.joinpath(vim.uv.cwd(), 'platformio.ini')
--   if vim.fn.filereadable(path) == 0 then
--     OS.notify(from .. 'platformio.ini not found in current working directory.', 'error')
--     return nil
--   end
--   -- local files = vim.fs.find('platformio.ini', {
--   --   path = vim.api.nvim_buf_get_name(0):match('(.*[/\\])') or vim.uv.cwd(),
--   --   upward = true,
--   --   stop = OS.defaultHome,
--   -- })
--   --
--   -- local path = files[1]
--   -- if not path then
--   --   OS.notify(msg .. 'platformio.ini not found.', 'error')
--   --   return nil
--   -- end
--
--   -- 2. Extract contents
--   local ok, content = misc.readFile(path)
--   if not ok or not content then
--     OS.notify(from .. 'Could not read platformio.ini at ' .. path, 'warn')
--     return nil
--   end
--
--   local default_envs_raw = ''
--   local valid_envs = {}
--   -- local env_ports = {} -- Map of environment configurations to their specified port profiles
--   -- local current_section = nil
--   local in_platformio_block = false
--
--
--
--   -- 3. Loop through lines with explicit, two-stage comment detection
--   for line in vim.gsplit(content, '[\r\n]+') do
--     print(line)
--     -- Strip semicolons (;) and hash (#) comments along with their leading/trailing whitespace
--     line = line:gsub('%s*[;#].*$', ''):gsub('^%s+', ''):gsub('%s+$', '')
--
--     -- Only evaluate the text row if it contains true, non-comment parameters properties
--     if line ~= '' then
--       local section = line:match('^%[(.+)%]$')
--       if section then
--         in_platformio_block = (section == 'platformio')
--
--         local env_name = section:match('^env:(.+)')
--         if env_name then
--           valid_envs[env_name] = true
--         end
--       end
--
--       -- Capture hardware target keys (e.g. upload_port = COM3 or /dev/ttyUSB0)
--       -- if current_section and current_section:match('^env:') then
--       --   local port_val = line:match('^upload_port%s*=%s*(.+)')
--       --   if port_val then
--       --     local env_name = current_section:match('^env:(.+)')
--       --     env_ports[env_name] = port_val
--       --   end
--       -- end
--
--       if in_platformio_block then
--         local def = line:match('^default_envs%s*=%s*(.*)')
--         if def then
--           default_envs_raw = def
--         end
--       end
--     end
--   end
--
--   -- -- Fetch physical hardware ports active right now
--   -- local connected_ports = get_connected_ports()
--   -- -- Helper closure to verify if an environment matches a plugged-in USB board
--   -- local function is_physically_connected(env_name)
--   --   local target_port = env_ports[env_name]
--   --   if not target_port then
--   --     return true
--   --   end -- If no port is locked in INI, default to true (auto-detect)
--   --   return connected_ports[target_port] == true
--   -- end
--
--   -- 4. CRITICAL RESOLUTION: Check if the cache contains any valid environments
--   if next(valid_envs) == nil then
--     OS.notify(from .. 'No active, environments found in platformio.ini', 'warn')
--     _G.metadata.active_env = ''
--     return nil
--   end
--
--   -- Priority 1: Keep the current active selection if it's still valid
--   if _G.metadata.active_env and valid_envs[_G.metadata.active_env] then
--     return _G.metadata.active_env
--   end
--
--   -- Priority 2: Fall back to the uncommented default_envs array parameters
--   if default_envs_raw ~= '' then
--     for env_name in default_envs_raw:gmatch('([^%s,]+)') do
--       if valid_envs[env_name] then
--         -- OS.notify(string.format(from .. ' get active_env1: %s', env_name), 'info')
--         _G.metadata.active_env = env_name
--         return env_name
--       end
--     end
--   end
--
--   -- 5. Fallback selection scanning matching active targets sequentially
--   -- for env_name, _ in pairs(valid_envs) do
--   --   if is_physically_connected(env_name) then
--   --     return env_name
--   --   end
--   -- end
--
--   -- Priority 3: Ultimate JIT fallback—grab the very first valid uncommented key
--   -- If Priorities 1 & 2 fail, this ensures a predictable return instead of leaking nil stack pointers
--   local first_valid = next(valid_envs)
--   if first_valid then
--     -- OS.notify(string.format(from .. ' get active_env2: %s', first_valid), 'info')
--     _G.metadata.active_env = first_valid
--     return first_valid
--   end
--
--   return nil
-- end
