-- lazy-loading technique using a Lua metatable.
-- It essentially "teaches" Neovim how to find a custom module only when you actually try to use it
-- setmetatable(vim, {
--   __index = function(t, k)
--     -- Lazy load the misc module if requested
--     if k == 'misc' then
--       t.misc = require('nvimpio.utils.misc')
--       return t.misc
--     end
--
--     -- Alias vim.pio to the pio module for convenience
--     if k == 'pio' then
--       t.pio = require('nvimpio.utils.pio')
--       return t.pio
--     end
--   end,
-- })

--@class vim
--@field pio platformio.utils.pio
--@field misc platformio.utils.misc

-- setmetatable(vim, {
--   __index = function(t, k)
--     if k == 'misc' then
--       local m = require('nvimpio.utils.misc')
--       rawset(t, k, m) -- Physically add 'misc' to 'vim'
--       return m
--     end
--     if k == 'pio' then
--       local p = require('nvimpio.utils.pio')
--       rawset(t, k, p) -- Physically add 'pio' to 'vim'
--       return p
--     end
--   end,
-- })
