local pio = require('nvimpio.pio.upkeep')

-- local M = {}

-- good
-- function M.select_env_picker()
--   if not _G.metadata or not _G.metadata.envs then
--     return
--   end
--   -- local current_active = _G.metadata.active_env
--   local current_active = pio.get_active_env('UI Picker: ')
--
--   -- 1. Harvest and sort your environment targets array list
--   local envs = {}
--   for env_name, _ in pairs(_G.metadata.envs) do
--     table.insert(envs, env_name)
--   end
--   table.sort(envs)
--
--   -- 2. Pass variables straight down to Neovim's selection core.
--   -- Because you already configured and loaded telescope's 'ui-select' extension
--   -- in your working pioTermList, it will automatically wrap this list into your
--   -- centered dropdown GUI look, honoring all row heights without collapsing!
--   vim.ui.select(envs, {
--     prompt = 'Select Active Target Environment:',
--     kind = 'nvimpio_env_selector',
--     format_item = function(name)
--       local idx = vim.fn.index(envs, name) + 1
--       -- Clean, universal text brackets guarantee no broken '?' character symbols
--       return string.format(' %d. %s %s', idx, (name == current_active) and '[x]' or '[ ]', name)
--     end,
--   }, function(choice)
--     if choice then
--       _G.metadata.active_env = choice
--       vim.cmd('redrawstatus') -- Instantly updates your radio buttons on your statusline
--       OS.notify(string.format('PlatformIO target swapped -> %s', choice), 'info')
--     end
--   end)
-- end

-- return M

-- local M = {}
--
-- function M.select_env_picker()
--   -- Assume your engine populated _G.metadata.envs with your target table
--   if not _G.metadata or not _G.metadata.envs then
--     return
--   end
--   local current_active = _G.metadata.active_env
--
--   -- 1. EXTRACT KEYS: Use pairs() to harvest the environment board names
--   local envs = {}
--   for env_name, _ in pairs(_G.metadata.envs) do
--     table.insert(envs, env_name)
--   end
--   table.sort(envs) -- Alphabetical sort for UI presentation
--
--   -- 2. Build the Centered Dropdown GUI Theme Geometry
--   local theme = require('telescope.themes').get_dropdown({
--     prompt_title = 'Select Environment',
--     results_title = 'Available Boards', -- Forces the window open, preventing collapsing bugs!
--     layout_config = { width = 38, height = #envs + 3 },
--     borderchars = {
--       prompt = { ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ' },
--       results = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
--       preview = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
--     },
--   })
--
--   -- 3. Execute the standard Telescope Dialogue Window Card
--   require('telescope.pickers')
--     .new(theme, {
--       initial_mode = 'insert', -- Immediate normal mode blocks command line typing inputs
--       finder = require('telescope.finders').new_table({
--         results = envs,
--         entry_maker = function(name)
--           local idx = vim.fn.index(envs, name) + 1
--           local checkbox = (name == current_active) and '[x]' or '[ ]' -- Universal font-safe format
--           return { value = name, display = string.format(' %d. %s %s', idx, checkbox, name), ordinal = name }
--         end,
--       }),
--       sorter = require('telescope.config').values.generic_sorter(theme),
--       attach_mappings = function(prompt_bufnr, map)
--         local make_selection = function()
--           local selection = require('telescope.actions.state').get_selected_entry()
--           require('telescope.actions').close(prompt_bufnr)
--           if selection then
--             _G.metadata.active_env = selection.value
--             vim.cmd('redrawstatus') -- Swaps your statusline indicators immediately
--             OS.notify(string.format('PlatformIO target swapped -> %s', selection.value), 'info')
--           end
--         end
--         map('n', '<CR>', make_selection)
--         map('n', '<Space>', make_selection)
--
--         -- Map Number Keys (1, 2, 3...) to trigger instant target updates
--         for idx = 1, math.min(#envs, 9) do
--           map('n', tostring(idx), function()
--             require('telescope.actions.state').get_current_picker(prompt_bufnr):set_selection(idx - 1)
--             make_selection()
--           end)
--         end
--         return true
--       end,
--     })
--     :find()
-- end
--
-- return M

-- local function select_env_picker()
--   local telescope = require('telescope')
--   telescope.setup({
--     extensions = {
--       ['ui-select'] = {
--         require('telescope.themes').get_dropdown({
--           borderchars = {
--             prompt = { ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ' },
--             results = { ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ' },
--             preview = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
--           },
--           prompt_position = 'top', -- "top" or "bottom"
--           -- prompt_prefix = '🔍 ', -- Prompt prefix
--           selection_caret = '❯ ', -- Selection indicator
--           entry_prefix = '  ', -- Entry prefix
--           initial_mode = 'insert', -- "insert" or "normal"
--           scroll_strategy = 'cycle', -- "cycle" or "limit"
--           sorting_strategy = 'ascending', -- "ascending" or "descending"
--           color_devicons = true, -- Color file icons
--           use_less = true, -- Use less for preview
--           -- prompt_prefix = " ",
--           -- selection_caret = " ",
--           -- color_devicons = true,
--         }),
--       },
--     },
--   })
--   telescope.load_extension('ui-select')
--   local current_active = pio.get_active_env('UI Picker: ')
--   if not current_active or not _G.metadata or not _G.metadata.envs then
--     return
--   end
--
--   local envs = {}
--   local id = 1
--   for name, _ in pairs(_G.metadata.envs) do
--     table.insert(envs, { id = id, name = name })
--     -- table.insert(envs, name)
--     id = id + 1
--   end
--   -- table.sort(envs)
--   --
--
--   if #envs == 0 then
--     OS.notify('No envs found.', 'warn')
--     return
--   end
--
--   vim.ui.select(envs, {
--     prompt = 'Select Active Target Environment:',
--     kind = 'nvimpio_env_selector',
--     format_item = function(item)
--       -- local idx = vim.fn.index(envs, name) + 1
--       -- Clean, universal text brackets guarantee no broken '?' character symbols
--       -- return string.format(' %d. %s %s', idx, (name == current_active) and '[x]' or '[ ]', name)
--       return string.format(' %d. %s %s', item.id, (item.name == current_active) and '[x]' or '[ ]', item.name)
--     end,
--     -- vim.ui.select(envs, {
--     --   prompt = 'Select Active env:',
--     --   kind = 'nvimpio_env_selector',
--     --
--     --   format_item = function(item)
--     --     return string.format('%d:%s %s', item.id, (item.name == current_active) and ' [●] ' or ' [○ ] ', item.name)
--     --   end,
--     --   -- Format your options with stylized checkboxes/radio buttons
--     --   -- format_item = function(name)
--     --   --   return (name == current_active) and (' [●] ' .. name) or (' [○ ] ' .. name)
--     --   -- end,
--   }, function(choice)
--     if choice then
--       -- Commit choice to global tracking contexts
--       _G.metadata.active_env = choice.name
--
--       -- Instantly update statusline markers
--       vim.cmd('redrawstatus')
--
--       OS.notify(string.format('PlatformIO active_env swapped -> %s', choice), 'info')
--     else
--       vim.api.nvim_echo({ { 'No environment target selected.', 'Normal' } }, true, {})
--     end
--   end)
-- end
--
-- return {
--   select_env_picker = select_env_picker,
-- }

-- local M = {}
--
-- function M.select_env_picker()
--   local current_active = pio.get_active_env('UI Picker: ')
--   if not current_active or not _G.metadata or not _G.metadata.envs then
--     return
--   end
--
--   local envs = {}
--   for name, _ in pairs(_G.metadata.envs) do
--     table.insert(envs, name)
--   end
--   table.sort(envs)
--
--   -- 1. Grab your working, centered dropdown geometry configuration base
--   local dropdown = require('telescope.themes').get_dropdown({
--     prompt_title = 'Select Environment',
--     layout_config = { width = 38 }, -- Remove height from here to prevent theme overriding
--     borderchars = {
--       prompt = { ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ' },
--       results = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
--       preview = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
--     },
--   })
--
--   -- 2. Force structural expansion dimensions directly inside the picker options table
--   require('telescope.pickers')
--     .new(dropdown, {
--       initial_mode = 'normal', -- Disables typing, allows arrow/number navigation instantly
--
--       -- THE CRITICAL GEOMETRY LOCK: Completely disables auto-shrinking loops!
--       results_height = #envs + 1,
--       dynamic_preview_title = true,
--
--       finder = require('telescope.finders').new_table({
--         results = envs,
--         entry_maker = function(name)
--           local idx = vim.fn.index(envs, name) + 1
--           local checkbox = (name == current_active) and '[x]' or '[ ]' -- Universal font safe
--           return { value = name, display = string.format(' %d. %s %s', idx, checkbox, name), ordinal = name }
--         end,
--       }),
--       sorter = require('telescope.config').values.generic_sorter(dropdown),
--       attach_mappings = function(prompt_bufnr, map)
--         local make_selection = function()
--           local selection = require('telescope.actions.state').get_selected_entry()
--           require('telescope.actions').close(prompt_bufnr)
--           if selection then
--             _G.metadata.active_env = selection.value
--             vim.cmd('redrawstatus') -- Instantly updates your radio buttons on your statusline
--             OS.notify(string.format('Swapped target -> %s', selection.value), 'info')
--           end
--         end
--         map('n', '<CR>', make_selection)
--         map('n', '<Space>', make_selection)
--
--         -- 3. Map Number Keys (1, 2, 3...) to trigger instant JIT selection updates
--         for idx = 1, math.min(#envs, 9) do
--           map('n', tostring(idx), function()
--             require('telescope.actions.state').get_current_picker(prompt_bufnr):set_selection(idx - 1)
--             make_selection()
--           end)
--         end
--         return true
--       end,
--     })
--     :find()
-- end
--
-- return M

-- local M = {}
--
-- function M.select_env_picker()
--   local current_active = pio.get_active_env('UI Picker: ')
--   if not current_active or not _G.metadata or not _G.metadata.envs then
--     return
--   end
--
--   -- 1. Build an optimized, numbered menu list using basic brackets
--   local menu_lines = { '--- Select Active Target Environment ---' }
--   local envs = {}
--   for name, _ in pairs(_G.metadata.envs) do
--     table.insert(envs, name)
--   end
--   table.sort(envs)
--
--   for idx, name in ipairs(envs) do
--     local checkbox = (name == current_active) and '[x]' or '[ ]'
--     table.insert(menu_lines, string.format('%d. %s %s', idx, checkbox, name))
--   end
--
--   -- 2. Trigger Neovim's native selection engine instantly
--   -- Users just tap numbers (1, 2, 3) or use arrows to select a board!
--   local choice = vim.fn.inputlist(menu_lines)
--   if choice > 0 and choice <= #envs then
--     _G.metadata.active_env = envs[choice]
--     vim.cmd('redrawstatus') -- Swaps your statusline indicators immediately
--     OS.notify(string.format('PlatformIO target swapped -> %s', envs[choice]), 'info')
--   end
-- end
--
-- return M

-- local M = {}
--
-- function M.select_env_picker()
--   -- 1. Refresh active environments data structures via your engine
--   local current_active = pio.get_active_env('UI Picker: ')
--   if not current_active or not _G.metadata or not _G.metadata.envs then
--     return
--   end
--
--   -- 2. Extract and sort environment board strings cleanly
--   local envs = {}
--   for name, _ in pairs(_G.metadata.envs) do
--     table.insert(envs, name)
--   end
--   table.sort(envs)
--
--   -- 3. Calculate perfectly centered structural dimensions
--   local ui = vim.api.nvim_list_uis()[1]
--   if not ui then
--     return
--   end
--
--   local width = 36
--   local height = #envs + 2 -- Enforces padding lines above and below
--   local row = math.floor((ui.height - height) / 2)
--   local col = math.floor((ui.width - width) / 2)
--
--   -- 4. Open a clean, native floating window card
--   local bufnr = vim.api.nvim_create_buf(false, true)
--   local win_id = vim.api.nvim_open_win(bufnr, true, {
--     relative = 'editor',
--     width = width,
--     height = height,
--     row = row,
--     col = col,
--     style = 'minimal',
--     border = 'rounded',
--     title = ' Select Target Environment ',
--     title_pos = 'center',
--   })
--
--   -- Configure buffer flags to prevent user text insertion modifications
--   vim.bo[bufnr].buftype = 'nofile'
--   vim.bo[bufnr].bufhidden = 'wipe'
--
--   -- 5. Build and render the display rows
--   local display_lines = { '' } -- Top padding line
--   local target_cursor_row = 2
--
--   for idx, name in ipairs(envs) do
--     local checkbox = (name == current_active) and '[x]' or '[ ]'
--     -- Prefixes explicit numbers for quick reference visibility maps
--     table.insert(display_lines, string.format('  %d. %s %s', idx, checkbox, name))
--     if name == current_active then
--       target_cursor_row = idx + 1
--     end
--   end
--   table.insert(display_lines, '') -- Bottom padding line
--
--   vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, display_lines)
--   vim.bo[bufnr].modifiable = false
--
--   -- Position the active line focus cursor straight out of the gate
--   pcall(vim.api.nvim_win_set_cursor, win_id, { target_cursor_row, 2 })
--
--   -- 6. Interaction Handlers (Window termination and execution states)
--   local function close_win()
--     if vim.api.nvim_win_is_valid(win_id) then
--       vim.api.nvim_win_close(win_id, true)
--     end
--   end
--
--   local function confirm_choice()
--     local cursor = vim.api.nvim_win_get_cursor(win_id)
--     local chosen_env = envs[cursor[1] - 1] -- Remove top padding offset to get true array item index
--     if chosen_env then
--       _G.metadata.active_env = chosen_env
--       vim.cmd('redrawstatus') -- Sync statusline radio selections instantly
--       close_win()
--       OS.notify(string.format('PlatformIO target swapped -> %s', chosen_env), 'info')
--     end
--   end
--
--   -- 7. Define navigation constraints and keyboard maps inside the menu card
--   local k_opts = { buffer = bufnr, silent = true, noremap = true }
--
--   -- Restrict arrow navigation loops from sliding out into empty padding regions
--   vim.keymap.set('n', 'j', function()
--     local r = vim.api.nvim_win_get_cursor(win_id)[1]
--     if r < #envs + 1 then
--       vim.cmd('normal! j')
--     end
--   end, k_opts)
--
--   vim.keymap.set('n', 'k', function()
--     local r = vim.api.nvim_win_get_cursor(win_id)[1]
--     if r > 2 then
--       vim.cmd('normal! k')
--     end
--   end, k_opts)
--
--   -- Selection maps
--   vim.keymap.set('n', '<CR>', confirm_choice, k_opts)
--   vim.keymap.set('n', '<Space>', confirm_choice, k_opts)
--
--   -- Quit windows maps
--   vim.keymap.set('n', '<Esc>', close_win, k_opts)
--   vim.keymap.set('n', 'q', close_win, k_opts)
--
--   -- 8. NUMBER KEY SHORTCUT MAPS: Typing '1', '2' chooses that environment row immediately
--   for idx = 1, math.min(#envs, 9) do
--     vim.keymap.set('n', tostring(idx), function()
--       -- Highlight the row line instantly and execute confirmation callbacks JIT
--       pcall(vim.api.nvim_win_set_cursor, win_id, { idx + 1, 2 })
--       confirm_choice()
--     end, k_opts)
--   end
-- end
--
-- return M
