-- local lspRestart = require('nvimpio.clangd.control').restart
-- lspRestart()

--  INFO: ['.clangd']
-- stylua: ignore
----------------------------------------------------------------------------------------
boilerplate['.clangd'] = {
  -- content = [[
  static = [[
---
CompileFlags:
  Remove: [
    "-mlongcalls",
    "-fstrict-volatile-bitfields",
    "-fno-tree-switch-conversion",
    "-mfix-esp32-psram-cache-issue",
    "-Wunknown-warning-option",
    "-fno-fat-lto-objects",
    "-fno-canonical-system-headers",
    "-mtext-section-literals",
    "-mlong-calls",
    "-march=.*",
    "-mabi=.*",
    "-mcpu=.*",
    "-fipa-pta.*",
    ]
  Add:  [
    "-xc++",
    "-std=gnu++17",
    "-Wno-unknown-argument",
    "-Wno-macro-redefined",
    "-Wno-invalid-token-paste",
    "-Wno-typedef-redefinition",
    "-Wno-unknown-attributes",
    "-Wno-pragma-system-header-outside-header",
    "-Wno-unknown-warning-option",
    "-Wno-unused-includes",
    ]
Diagnostics:
  Suppress:  [
    "macro_too_many_args",
    "unused_macro_definition",
    "pp_file_not_found",
    "pp_file_not_found_angled_not_fatal",
    "pp_included_file_not_found",
    "pp_including_mainfile_in_preamble",
    "unused-includes",
    "misc-definitions-in-headers",
    ]
  ClangTidy:
    Remove: ["readability-*", "modernize-*", "bugprone-*", "cert-err58-cpp"]
]],

  dynamic = [[
---
# Dynamic configuration block generated by nvim-pio
CompileFlags:
  Remove: [
    %s
    ]
Diagnostics:
  Suppress:  [
    %s
  ]
]],
    --"drv_unknown_argument",
  content = function(self)
    local core = require('nvimpio')
    local cwdClangd = misc.joinPath(vim.uv.cwd(), '.clangd')
    local coreClangd = misc.joinPath(core.config.pio_storage_dir, '.clangd')
    local staticBlock, dynamicBlock = '', ''

    if vim.uv.fs_stat(cwdClangd) then
      local ok, content = misc.readFile(cwdClangd)

      if not ok or not content then return nil end

      -- Strip out any previous dynamic blocks to prevent endless growing
      if ok then staticBlock = content:gsub('\n%-%-%-\n# Dynamic configuration block generated by nvim%-pio.*', '') end
    else staticBlock = self.static end

    local args = M.args or {}
    dynamicBlock = string.format(self.dynamic, table.concat(args, ',\n    '))

    local final_content = staticBlock .. '\n' .. dynamicBlock

    misc.writeFile(cwdClangd, final_content, {})
    misc.writeFile(coreClangd, final_content, {})
    return final_content
  end,

}
