-- local M = {}
--
-- -- ============================================================================
-- -- 0. NATIVE PATH EXPANDER (Fully Resolves Tildes, Drive Casing, and Slashes)
-- -- ============================================================================
-- local function normalize_absolute_path(path)
--   if not path or path == '' then
--     return ''
--   end
--   local expanded = vim.fn.fnamemodify(path, ':p')
--   return vim.fs.normalize(expanded):lower()
-- end
--
-- -- ============================================================================
-- -- 1. THE ENTERPRISE 0.11+ DECLARATIVE REGISTRATION (The Simplified Core Way)
-- -- ============================================================================
-- function M.activate_workspace_engine()
--   local server_name = 'clangd'
--
--   vim.lsp.config(server_name, {
--     cmd = {
--       'clangd',
--       '--background-index',
--       '--clang-tidy',
--       '--completion-style=detailed',
--       '--pch-storage=memory',
--       '-j=4',
--       -- Fixed project data is declared statically right at the root layer
--       '--compile-commands-dir=C:/Users/batoaqaa/AppData/Local/ahmed/test',
--       '--query-driver=C:/Users/batoaqaa/.platformio/packages/toolchain-**/*',
--     },
--     filetypes = { 'c', 'cpp', 'objc', 'objcpp' },
--     capabilities = vim.lsp.protocol.make_client_capabilities(),
--     init_options = {
--       ['clangdFileStatus'] = true,
--       ['completeUnimported'] = true,
--       ['usePlaceholders'] = true,
--     },
--
--     -- NATIVE CRITERIA: Pass markers straight to the core engine.
--     root_markers = { 'platformio.ini', 'CMakeLists.txt', '.git' },
--
--     -- NATIVE REUSE: Strict string path validation prevents cross-folder client bleed
--     reuse_client = function(client, config)
--       if client.name ~= server_name then
--         return false
--       end
--
--       local proposed_root = config.root_dir
--       local running_client_root = client.config.root_dir or client.root_dir
--
--       if not proposed_root or not running_client_root then
--         return false
--       end
--
--       return normalize_absolute_path(running_client_root) == normalize_absolute_path(proposed_root)
--     end,
--   })
--
--   -- Natively activate the declaration matrix
--   if not vim.lsp.is_enabled(server_name) then
--     vim.lsp.enable(server_name, true)
--   end
-- end
--
-- -- ============================================================================
-- -- 2. THE NATIVE 0.11+ RESET ENGINE (Pure State Cycling, Zero Bloat)
-- -- ============================================================================
-- function M.restart()
--   local name = 'clangd'
--   local current_buf = vim.api.nvim_get_current_buf()
--
--   -- 1. Isolate the running client instance bound to this buffer space
--   local old_client = nil
--   for _, client in ipairs(vim.lsp.get_clients({ name = name, bufnr = current_buf })) do
--     old_client = client
--     break
--   end
--
--   -- Fallback if no server is running yet: safely toggle the declarative state
--   if not old_client then
--     print('[LSP Engine] Initializing configuration engine blocks...')
--     if not vim.lsp.is_enabled(name) then
--       vim.lsp.enable(name, true)
--     end
--     return
--   end
--
--   local old_id = old_client.id
--   print('[LSP Engine] Initiating 100% clean core reset for client ID: ' .. old_id)
--
--   -- 2. Create a clean one-shot listener group to await absolute client unregistration
--   local reload_group = vim.api.nvim_create_augroup('Clangd_Cold_Reset_Engine', { clear = true })
--
--   vim.api.nvim_create_autocmd('LspDetach', {
--     group = reload_group,
--     desc = 'Re-activate state schemas the microsecond the old channel is deleted from memory',
--     callback = function(args)
--       if args.data.client_id == old_id then
--         vim.api.nvim_del_augroup_by_id(reload_group)
--
--         -- 3. Yield securely to the next event loop tick to ensure registries are fully empty
--         vim.schedule(function()
--           print('[LSP Engine] Channels flushed. Re-enabling pure declarative workspace structures...')
--
--           -- Cycling the declarative state forces Neovim's native supervisor to re-evaluate
--           -- every active file buffer, check the root string mutations, and spawn a fresh client.
--           vim.lsp.enable(name, false)
--           vim.lsp.enable(name, true)
--
--           print('[LSP Engine] Dynamic cold-boot complete.')
--         end)
--       end
--     end,
--   })
--
--   -- 4. Polite object-oriented SIGTERM allows clangd to flush indexing logs and exit with code 0
--   old_client:stop(false)
-- end
--
-- -- Expose entry points as clean runtime commands
-- vim.api.nvim_create_user_command('ClangdReloadScratch', M.restart, {})
--
-- -- ============================================================================
-- -- 3. AUTOMATED ENVIRONMENT WATCHER
-- -- ============================================================================
-- local pio_config_group = vim.api.nvim_create_augroup('PlatformIO_LSP_Config_Watcher', { clear = true })
-- vim.api.nvim_create_autocmd('BufWritePost', {
--   group = pio_config_group,
--   pattern = 'platformio.ini',
--   callback = function()
--     vim.schedule(function()
--       M.restart()
--     end)
--   end,
-- })
--
-- return M
