-- function M.restart()
--   local name = 'clangd'
--
--   -- 1. Scan for the active runtime client using the modern 0.11+ API
--   local old_client = nil
--   for _, client in ipairs(vim.lsp.get_clients({ name = name })) do
--     old_client = client
--     break
--   end
--
--   -- If no server is currently active, apply the configuration and boot instantly
--   if not old_client then
--     vim.lsp.config(name, M.getClangdConfig())
--     vim.lsp.enable(name, true)
--     print('[LSP Engine] Pristine clangd instance initialized.')
--     return
--   end
--
--   -- 2. Capture session parameters cleanly
--   local old_id = old_client.id
--   local active_buffers = vim.lsp.get_buffers_by_client_id(old_id)
--
--   print('[LSP Engine] Initiating clean architectural shutdown for client ID: ' .. old_id)
--
--   -- 3. THE DEFINITIVE EVENT-DRIVEN REGISTRATION (No hacks, No extra parameters)
--   -- Create a temporary autocommand group to wait for the specific client to finish detaching
--   local reload_group = vim.api.nvim_create_augroup('Clangd_Cold_Reset_Engine', { clear = true })
--
--   vim.api.nvim_create_autocmd('LspDetach', {
--     group = reload_group,
--     desc = 'Block execution until Neovim confirms absolute client unregistration',
--     callback = function(args)
--       -- Verify that the detaching client is exactly our target instance
--       if args.data.client_id == old_id then
--         -- Immediately delete this autocommand group to clean up memory footprints
--         vim.api.nvim_del_augroup_by_id(reload_group)
--
--         -- Safe to yield execution to a schedule pass now that registries are empty
--         vim.schedule(function()
--           -- Declaratively clear stale attachment metadata spaces cleanly
--           vim.lsp.enable(name, false)
--
--           -- Apply fresh configuration profiles safely
--           vim.lsp.config(name, M.getClangdConfig())
--
--           -- Boot the perfectly clean, non-colliding background process daemon
--           local success = pcall(vim.lsp.enable, name, true)
--
--           if success then
--             -- Re-attach all collected open project file buffers immediately
--             vim.schedule(function()
--               local new_client = nil
--               for _, n_client in ipairs(vim.lsp.get_clients({ name = name })) do
--                 new_client = n_client
--                 break
--               end
--
--               if new_client then
--                 for _, buf in ipairs(active_buffers) do
--                   if vim.api.nvim_buf_is_valid(buf) then
--                     vim.lsp.buf_attach_client(buf, new_client.id)
--                   end
--                 end
--                 print('[LSP Engine] clangd successfully cold-booted from scratch (New ID: ' .. new_client.id .. ').')
--               end
--             end)
--           else
--             vim.notify('[LSP Engine Error] Failed to re-enable clangd engine configuration.', vim.log.levels.ERROR)
--           end
--         end)
--       end
--     end,
--   })
--
--   -- 4. Execute the modern object-oriented shutdown method cleanly
--   -- Passing 'false' sends a polite SIGTERM so clangd can exit with code 0.
--   old_client:stop(false)
-- end
