local M = {}

local misc = require('nvimpio.utils.misc')
M.core_dir = ''
-- M.args = {}
-- Initialize the communication arrays globally inside the module container
-- M.remove = {}
-- M.suppress = {}

local boilerplate = {}

-- INFO: main.cpp
--- stylua: ignore
----------------------------------------------------------------------------------------
boilerplate['main.cpp'] = {
  rewrite = false,
  read = false,
  content = [[
#include "main.hpp"

void setup() { }

void loop() { }
]],
}

-- INFO: main.hpp
--- stylua: ignore
----------------------------------------------------------------------------------------
boilerplate['main.hpp'] = {
  rewrite = false,
  read = false,
  content = [[
#ifndef mainHEAD
#define mainHEAD

#include <Arduino.h>

#endif
]],
}

-- INFO: platformio.ini
----------------------------------------------------------------------------------------
boilerplate['platformio.ini'] = {
  rewrite = false,
  read = false,
  template = [[
[platformio]
core_dir = %s
platforms_dir = ${platformio.core_dir}/platforms
packages_dir = ${platformio.core_dir}/packages
;libdeps_dir = ./external_libs

default_envs =
;default_envs = uno, nodemcu

;--------------------------------------------------------------------------
[env]
framework = arduino
upload_speed = 115200
monitor_speed = 9600

monitor_rts = 1   ; 1 combination to reset esp32c6 (Table 32.3-2. CDC-ACM Settings with RTS and DTR)
monitor_dtr = 0   ; 0 // pio dev mon --rts=0 --dtr=0 then pio dev mon --rts=1 dtr=0

extra_scripts =
  ;post:generate_compileDB.py
  ;pre:enable_toolchain.py ; enabled global env 'PLATFORMIO_SETTING_COMPILATIONDB_INCLUDE_TOOLCHAIN'

lib_ldf_mode = chain   ;Library dependencies Finder ldf


]],
  content = function(self)
    local core_dir = require('nvimpio').config.pio_storage_dir

    return string.format(self.template, core_dir)
  end,
}

-- "-ferror-limit=0",
-- "-std=c++17"
-- "--log=verbose",
-- Note: %q is used for paths to handle escaping and spaces automatically.
-- INFO: .clangd_config
----------------------------------------------------------------------------------------
boilerplate['.clangdConfig.json'] = {
  rewrite = false,
  read = true,
  content = [[
{
  "cmd": [
    "clangd",
    "--enable-config",
    "--limit-results=100",
    "--background-index",
    "--background-index-priority=low",
    "--all-scopes-completion",
    "--clang-tidy",
    "--compile_args_from=filesystem",
    "--completion-parse=always",
    "--completion-style=detailed",
    "--header-insertion=iwyu",
    "--fallback-style=llvm",
    "--log=error",
    "--pch-storage=memory",
    "--pretty",
    "--ranking-model=decision_forest",
    "--query-driver=%s"
  ],
  "filetypes": [
    "c",
    "cpp",
    "objc",
    "objcpp",
    "cuda",
    "proto"
  ],
  "init_options": {
    "clangdFileStatus": true,
    "completeUnimported": true,
    "fallbackFlags": [
    ],
    "usePlaceholders": true
  },
  "root_markers": [
    "platformio.ini",
    "CMakeLists.txt",
    ".clangd",
    ".clang-tidy",
    ".clang-format",
    "compile_commands.json",
    "compile_flags.txt",
    "configure.ac",
    ".git"
  ],
  "single_file_support": true,
  "workspace_required": true
}
]],
}

boilerplate['.clangd'] = {
  static = [[
---
CompileFlags:
  Remove: [
    ]
  Add:  [
    ]
Diagnostics:
  Suppress:  [
    ]
  ClangTidy:
    Remove: ["readability-*", "modernize-*", "bugprone-*", "cert-err58-cpp"]
]],

  dynamic = [[
---
# Dynamic configuration block generated by nvim-pio
CompileFlags:
  CompilationDatabase: %q
  Remove: [
    %s
    ]
  Add: [
    "@%s"
    ]
]],
  content = function(self, project_root_param)
    local core = require('nvimpio')
    local project_root = project_root_param or vim.g.platformioRootDir or vim.uv.cwd() or '.'
    project_root = vim.fs.normalize(project_root)

    local cwdClangd = vim.fs.joinpath(OS.project_dir, '.clangd')
    local coreClangd = vim.fs.joinpath(core.config.pio_storage_dir, '.clangd')
    local flagsFile = OS.clangd_flags
    local filter_db_path = OS.clangd_filter
    local staticBlock, dynamicBlock = '', ''

    if vim.uv.fs_stat(cwdClangd) then
      local ok, content = misc.readFile(cwdClangd)
      if ok and content then
        staticBlock = content:gsub('\n%-%-%-\n# Dynamic configuration block generated by nvim%-pio.*', '')
      end
    else
      staticBlock = self.static
    end

    -- A: Force-create an empty default database if missing
    local db_exist = vim.uv.fs_stat(filter_db_path)
    if not db_exist then
      local default_db = { codes = {}, flags = {} }
      local f_init = io.open(filter_db_path, 'wb')
      if f_init then
        f_init:write(misc.jsonFormat and misc.jsonFormat(default_db) or '{\n  "codes": {},\n  "flags": {}\n}')
        f_init:close()
      end
    end

    -- 1. HYDRODYNAMIC SYNC (WITH DIRECT DISK FALLBACK GATING):
    local removed_args = {}
    local flags_dictionary = {}

    local success, pio_diag = pcall(require, 'nvimpio.clangd.diagnostic')
    if success and pio_diag and pio_diag.removed_flags and next(pio_diag.removed_flags) then
      for flag, is_blocked in pairs(pio_diag.removed_flags) do
        flags_dictionary[flag] = is_blocked
      end
    else
      local f = io.open(filter_db_path, 'r')
      if f then
        local raw = f:read('*a')
        f:close()
        if raw and raw ~= '' then
          local ok, data = pcall(vim.json.decode, raw)
          if ok and data and type(data.flags) == 'table' then
            for flag, blocked in pairs(data.flags) do
              if blocked then
                flags_dictionary[flag] = true
              end
            end
          end
        end
      end
    end

    for flag, is_blocked in pairs(flags_dictionary) do
      if is_blocked and type(flag) == 'string' and flag ~= '' then
        table.insert(removed_args, flag)
      end
    end
    table.sort(removed_args)

    local formatted_removed_args = {}
    for i = 1, #removed_args do
      table.insert(formatted_removed_args, string.format('%q', removed_args[i]))
    end

    -- 2. METADATA EXTRACTOR
    local options_file_lines = {}
    local target_meta = nil

    if _G.metadata then
      -- Target A: Check if properties sit directly on the flat root table
      if _G.metadata.includes_build or _G.metadata.auto_defines then
        target_meta = _G.metadata
      else
        -- Target B: Dynamic deep scan loop. Extract data from the first active nested sub-table env block
        for _, sub_table in pairs(_G.metadata) do
          if type(sub_table) == 'table' and (sub_table.includes_build or sub_table.auto_defines) then
            target_meta = sub_table
            break
          end
        end
      end
    end

    -- local log_file = vim.fs.joinpath(project_root, 'nvim_pio_boot_trace.log')
    -- local f_log = io.open(log_file, 'a')

    if target_meta then
      -- -- 🔍 TRACE LOGGING: Record successful dynamic extraction parameters
      -- if f_log then
      --   local timestamp = os.date('%Y-%m-%d %H:%M:%S')
      --   f_log:write(string.format('[%s] 🟢 NESTED DATA FOUND! Unpacking include pools...\n', timestamp))
      --   f_log:close()
      --   f_log = nil
      -- end

      -- -- Phase A: Extract board macro defines safely
      -- if type(target_meta.auto_defines) == 'table' then
      --   for i = 1, #target_meta.auto_defines do
      --     local define = target_meta.auto_defines[i]
      --     if type(define) == 'string' and define ~= '' then
      --       table.insert(options_file_lines, define)
      --     end
      --   end
      -- end

      -- 🟢  phase A: UNIFIED MACRO DEFINITIONS POOL TRAVERSAL
      local define_pools = {
        target_meta.auto_defines,
        target_meta.defines,
      }

      -- High-performance JIT-optimized loop for all definitions pools
      for pool_idx = 1, #define_pools do
        local pool = define_pools[pool_idx]
        if type(pool) == 'table' then
          for flag_idx = 1, #pool do
            local define = pool[flag_idx]
            if type(define) == 'string' and define ~= '' then
              -- Safely check if it already starts with "-D". If not, prepend it.
              local formatted_define = define:match('^%-D') and define or ('-D' .. define)
              table.insert(options_file_lines, formatted_define)
            end
          end
        end
      end

      -- 🟢  Phase B: Extract all pre-sorted path flags using JIT sequential loops
      local include_pools = {
        -- target_meta.includes_libdeps,
        -- target_meta.includes_build,
        -- target_meta.includes_toolchain,
        -- target_meta.includes_compatlib,
      }

      table.insert(options_file_lines, '-I.pio/libdeps/seeed_xiao_esp32c3/ArduinoJson/src/ArduinoJson/Variant/../../../../')
      table.insert(
        options_file_lines,
        '-IC:/VSCode/data/Projects/Digital-Wall-Clock-Long-ESP32C3-Pray5/.pio/libdeps/seeed_xiao_esp32c3/ArduinoJson/src/ArduinoJson/../../'
      )
      for pool_idx = 1, #include_pools do
        local pool = include_pools[pool_idx]
        for flag_idx = 1, #(pool or {}) do
          local raw_flag = pool[flag_idx]
          if type(raw_flag) == 'string' and raw_flag ~= '' then
            table.insert(options_file_lines, vim.fs.normalize(raw_flag))
          end
        end
      end

      -- 🟢  Phase C: Write fresh data lines out to disk
      local final_flags_content = table.concat(options_file_lines, '\n')
      local pio_build_dir = vim.fs.dirname(flagsFile)
      if not vim.uv.fs_stat(pio_build_dir) then
        vim.fn.mkdir(pio_build_dir, 'p')
      end

      local f_ok, old_flags = misc.readFile(flagsFile)
      if not f_ok or old_flags ~= final_flags_content then
        misc.writeFile(flagsFile, final_flags_content, {})
      end
    else
      -- -- 🔍 TRACE LOGGING: Record if lookup continues failing across all levels
      -- if f_log then
      --   local timestamp = os.date('%Y-%m-%d %H:%M:%S')
      --   f_log:write(string.format('[%s] ⚠️  Structural scan failed. Metadata properties unreachable.\n', timestamp))
      --   f_log:close()
      -- end

      local flags_exist = vim.uv.fs_stat(flagsFile)
      if not flags_exist then
        local pio_build_dir = vim.fs.dirname(flagsFile)
        if not vim.uv.fs_stat(pio_build_dir) then
          vim.fn.mkdir(pio_build_dir, 'p')
        end
        misc.writeFile(flagsFile, '', {})
      end
    end

    print(OS.project_dir)
    -- 3. ASSEMBLE CLEAN MAIN .CLANGD STRINGS PROFILE
    dynamicBlock = string.format(self.dynamic, OS.project_dir, table.concat(formatted_removed_args, ',\n    '), OS.clangd_flags)
    local final_content = staticBlock .. '\n' .. dynamicBlock

    -- 4. UNCONDITIONAL DISK WRITER MATRIX
    local read_ok, old_content = misc.readFile(cwdClangd)
    if not read_ok or old_content ~= final_content then
      misc.writeFile(cwdClangd, final_content, {})
      misc.writeFile(coreClangd, final_content, {})

      vim.schedule(function()
        for _, client in ipairs(vim.lsp.get_clients({ name = 'clangd' })) do
          if client and type(client.notify) == 'function' then
            client:notify('workspace/didChangeConfiguration', { settings = {} })
          end
        end
      end)
    end

    return final_content
  end,
}
-- INFO: .clang-format
----------------------------------------------------------------------------------------
boilerplate['.clang-format'] = {
  rewrite = false,
  read = false,
  content = [[
# clang-format configurator
# https://clang-format-configurator.site
---
BasedOnStyle: Google  # LLVM, Google, Chromium, Mozilla, WebKit, Microsoft, Linux
AccessModifierOffset: -4
AllowShortCaseExpressionOnASingleLine: All
AllowShortFunctionsOnASingleLine: All
BreakBeforeBraces: Attach # Allman
ColumnLimit: 100
IndentWidth: 4
KeepEmptyLinesAtTheStartOfBlocks: true
PointerAlignment: Right
SortIncludes: true
ReflowComments: true
SpaceBeforeParens: ControlStatements
ConstructorInitializerIndentWidth: 4
PackConstructorInitializers: Never
...
]],
}

-- INFO: boilerplate_gen
--- stylua: ignore
----------------------------------------------------------------------------------------
function M.boilerplate_gen(framework, src_path, filename, from)
  filename = filename or framework
  src_path = src_path or ''
  from = from or 'here'

  local entry = boilerplate[framework]
  if not entry then
    return ''
  end

  if framework == '.clangd' then
    return entry:content()
  end

  local file_path = vim.fs.joinpath(src_path, filename)

  if vim.uv.fs_stat(file_path) then
    if not entry.rewrite then
      if entry.read then
        local ok, content = misc.readFile(file_path)
        -- if ok then print(content) end
        if ok then
          return content
        end
        -- local fr = io.open(file_path, 'r')
        -- if fr then return (fr:read('*a')) end
      end
      return ''
    end
  end
  --
  local template = type(entry.content) == 'function' and entry:content() or entry.content
  misc.writeFile(file_path, template, {})

  if entry.read then
    return template
  else
    return ''
  end
end

return M
