local M = {}

local misc = require('nvimpio.utils.misc')
M.core_dir = ''
M.args = {}

local boilerplate = {}

-- INFO: main.cpp
--- stylua: ignore
----------------------------------------------------------------------------------------
boilerplate['main.cpp'] = {
  rewrite = false,
  read = false,
  content = [[
#include "main.hpp"

void setup() { }

void loop() { }
]],
}

-- INFO: main.hpp
--- stylua: ignore
----------------------------------------------------------------------------------------
boilerplate['main.hpp'] = {
  rewrite = false,
  read = false,
  content = [[
#ifndef mainHEAD
#define mainHEAD

#include <Arduino.h>

#endif
]],
}

-- INFO: platformio.ini
----------------------------------------------------------------------------------------
boilerplate['platformio.ini'] = {
  rewrite = false,
  read = false,
  template = [[
[platformio]
core_dir = %s
platforms_dir = ${platformio.core_dir}/platforms
packages_dir = ${platformio.core_dir}/packages
;libdeps_dir = ./external_libs

default_envs =
;default_envs = uno, nodemcu

;--------------------------------------------------------------------------
[env]
framework = arduino
upload_speed = 115200
monitor_speed = 9600

monitor_rts = 1   ; 1 combination to reset esp32c6 (Table 32.3-2. CDC-ACM Settings with RTS and DTR)
monitor_dtr = 0   ; 0 // pio dev mon --rts=0 --dtr=0 then pio dev mon --rts=1 dtr=0

extra_scripts =
  ;post:generate_compileDB.py
  ;pre:enable_toolchain.py ; enabled global env 'PLATFORMIO_SETTING_COMPILATIONDB_INCLUDE_TOOLCHAIN'

lib_ldf_mode = chain   ;Library dependencies Finder ldf

;[env:seeed_xiao_esp32c3]
;platform = espressif32
;board = seeed_xiao_esp32c3

]],
  content = function(self)
    return string.format(self.template, M.core_dir)
  end,
}

-- Note: %q is used for paths to handle escaping and spaces automatically.
-- INFO: .clangd_config
----------------------------------------------------------------------------------------
boilerplate['.clangd_config.json'] = {
  rewrite = false,
  read = true,
  content = [[
{
  "cmd": [
    "clangd",
    "--all-scopes-completion",
    "--background-index",
    "--clang-tidy",
    "--compile_args_from=filesystem",
    "--enable-config",
    "--completion-parse=always",
    "--completion-style=detailed",
    "--header-insertion=iwyu",
    "--fallback-style=llvm",
    "--log=verbose",
    "--pch-storage=memory",
    "--pretty",
    "--ranking-model=decision_forest",
    "--sync",
    "--offset-encoding=utf-16",
    "--query-driver=%s"
  ],
  "filetypes": [
    "c",
    "cpp",
    "objc",
    "objcpp",
    "cuda",
    "proto"
  ],
  "init_options": {
    "clangdFileStatus": true,
    "compilationDatabasePath": ".",
    "completeUnimported": true,
    "fallbackFlags": [

    ],
    "usePlaceholders": true
  },
  "root_markers": [
    "platformio.ini",
    "CMakeLists.txt",
    ".clangd",
    ".clang-tidy",
    ".clang-format",
    "compile_commands.json",
    "compile_flags.txt",
    "configure.ac",
    ".git"
  ],
  "single_file_support": true,
  "workspace_required": true
}
]],
}

--  INFO: ['.clangd']
-- stylua: ignore
----------------------------------------------------------------------------------------
boilerplate['.clangd'] = {
  -- content = [[
  static = [[
---
CompileFlags:
  Remove: [
    "-Wunknown-warning-option",
    "-fno-tree-switch-conversion",
    "-fno-fat-lto-objects",
    "-fno-canonical-system-headers",
    "-mtext-section-literals",
    "-mlong-calls",
    "-fstrict-volatile-bitfields",
    "-march=.*",
    "-mabi=.*",
    "-mcpu=.*",
    "-fipa-pta.*",
    ]
  Add:  [
    "-xc++",
    "-std=gnu++17",
    "-Wno-pragma-system-header-outside-header",
    "-Wno-unknown-warning-option",
    "-Wno-unused-includes",
    ]
Diagnostics:
  Suppress:  [
    "drv_unknown_argument",
    "pp_file_not_found",
    "pp_file_not_found_angled_not_fatal",
    "pp_included_file_not_found",
    "pp_including_mainfile_in_preamble",
    "unused-includes",
    "misc-definitions-in-headers",
    ]
  ClangTidy:
    Remove: ["readability-*", "modernize-*", "bugprone-*", "cert-err58-cpp"]
]],

  dynamic = [[
---
# Dynamic configuration block generated by nvim-pio
CompileFlags:
  Remove: [
    %s
    ]
]],
  content = function(self)
    local cwdClangd = misc.joinPath(vim.uv.cwd(), '.clangd')
    local coreClangd = misc.joinPath(M.core_dir, '.clangd')
    local staticBlock, dynamicBlock = '', ''

    if vim.uv.fs_stat(cwdClangd) then
      local ok, content = misc.readFile(cwdClangd)

      if not ok or not content then return nil end

      -- Strip out any previous dynamic blocks to prevent endless growing
      if ok then staticBlock = content:gsub('\n%-%-%-\n# Dynamic configuration block generated by nvim%-pio.*', '') end
    else staticBlock = self.static end

    local args = M.args or {}
    dynamicBlock = string.format(self.dynamic, table.concat(args, ',\n    '))

    local final_content = staticBlock .. '\n' .. dynamicBlock

    misc.writeFile(cwdClangd, final_content, {})
    misc.writeFile(coreClangd, final_content, {})
    return final_content
  end,

}

-- INFO: .clang-format
----------------------------------------------------------------------------------------
boilerplate['.clang-format'] = {
  rewrite = false,
  read = false,
  content = [[
# clang-format configurator
# https://clang-format-configurator.site
---
BasedOnStyle: Google  # LLVM, Google, Chromium, Mozilla, WebKit, Microsoft, Linux
AccessModifierOffset: -4
AllowShortCaseExpressionOnASingleLine: All
AllowShortFunctionsOnASingleLine: All
BreakBeforeBraces: Attach # Allman
ColumnLimit: 100
IndentWidth: 4
KeepEmptyLinesAtTheStartOfBlocks: true
PointerAlignment: Right
SortIncludes: true
ReflowComments: true
SpaceBeforeParens: ControlStatements
ConstructorInitializerIndentWidth: 4
PackConstructorInitializers: Never
...
]],
}

-- INFO: boilerplate_gen
-- stylua: ignore
----------------------------------------------------------------------------------------
function M.boilerplate_gen(framework, src_path, filename)
  filename = filename or framework
  local entry = boilerplate[framework]
  if not entry then return '' end

  if framework == '.clangd' then return entry:content() end

  local file_path = vim.fs.normalize(src_path .. '/' .. filename)

  if vim.uv.fs_stat(file_path) then
    if not entry.rewrite then
      if entry.read then
        local ok, content = misc.readFile(file_path)
        -- if ok then print(content) end
        if ok then return content end
        -- local fr = io.open(file_path, 'r')
        -- if fr then return (fr:read('*a')) end
      end
      return ''
    end
  end
  --
  local template = type(entry.content) == 'function' and entry:content() or entry.content
  misc.writeFile(file_path, template, {})

  if entry.read then
    return template
  else return '' end
end

return M
