local M = {}

-- ====================================================================
-- HELPERS FOR STRUCTURAL FILE INJECTION
-- ====================================================================
local function get_local_clangd_path()
  local current_buf = vim.api.nvim_get_current_buf()
  local current_file = vim.api.nvim_buf_get_name(current_buf)
  local root_markers = { 'platformio.ini', '.git', '.clangd' }
  local root_dir = vim.fs.root(current_file, root_markers) or vim.fn.getcwd()
  return root_dir .. '/.clangd'
end

local function ensure_baseline_template()
  local local_clangd_file = get_local_clangd_path()
  local f_check = io.open(local_clangd_file, 'r')
  if not f_check then
    local f_init = io.open(local_clangd_file, 'wb')
    if f_init then
      local baseline_template = [[
CompileFlags:
  Remove: []
  Add:
    [
      "-xc++",
      "-std=gnu++17",
      "-Wno-unknown-argument",
      "-Wno-macro-redefined",
      "-Wno-invalid-token-paste",
      "-Wno-typedef-redefinition",
      "-Wno-unknown-attributes",
      "-Wno-pragma-system-header-outside-header",
      "-Wno-unknown-warning-option",
      "-Wno-unused-includes",
    ]
Diagnostics:
  Suppress:
    [
      "macro_too_many_args",
      "unused_macro_definition",
      "pp_file_not_found",
      "pp_file_not_found_angled_not_fatal",
      "pp_included_file_not_found",
      "pp_including_mainfile_in_preamble",
      "unused-includes",
      "misc-definitions-in-headers",
    ]
  ClangTidy:
    Remove: ["readability-*", "modernize-*", "bugprone-*", "cert-err58-cpp"]

---
# Dynamic configuration block generated by nvim-pio
CompileFlags:
  Remove: [
    "-mlongcalls",
    "-fstrict-volatile-bitfields",
    "-fno-tree-switch-conversion"
    ]
]]
      f_init:write(baseline_template)
      f_init:close()
    end
  else
    f_check:close()
  end
end

local function inject_batch_into_clangd(items_list)
  ensure_baseline_template()
  local local_clangd_file = get_local_clangd_path()

  -- 1. Read existing file contents into memory safely
  local file_content = ''
  local f_read = io.open(local_clangd_file, 'rb')
  if f_read then
    file_content = f_read:read('*all')
    f_read:close()
  end

  -- Normalize incoming tokens list to filter true new changes
  local flags_to_add = {}
  local codes_to_add = {}
  local internal_has_new = false

  for _, item in ipairs(items_list) do
    local is_driver_flag = string.match(tostring(item.code):lower(), '^drv_')
      or string.match(item.message:lower(), 'unknown argument')
      or string.match(item.message:lower(), '%-mlongcalls')

    if is_driver_flag then
      local extracted_flag = string.match(item.message, '[\'"](%-.-)[\'"]') or string.match(item.message, '%s(%-.*)%s')
      if not extracted_flag then
        extracted_flag = string.match(item.message, 'argument%s+(%-.*)$') or '-mlongcalls'
      end
      local clean_flag = vim.trim(extracted_flag):gsub('[\',;"%s]', '')

      -- Verify with explicit quote inclusion guards
      if not string.find(file_content, '"' .. clean_flag .. '"', 1, true) then
        flags_to_add[clean_flag] = true
        internal_has_new = true
      end
    else
      local clean_code = vim.trim(tostring(item.code or '')):gsub('[\',;"%s]', '')
      if clean_code ~= '' and clean_code ~= 'uncategorized_noise' then
        if not string.find(file_content, clean_code, 1, true) then
          codes_to_add[clean_code] = true
          internal_has_new = true
        end
      end
    end
  end

  -- If everything is already suppressed inside the file, exit cleanly
  if not internal_has_new then
    return false
  end

  -- 2. Line-by-Line Surgical Stream Builder (Windows Carriage Return Safe)
  local output_lines = {}
  local in_dynamic_block = false
  local in_remove_array = false
  local has_diagnostics_block = string.find(file_content, 'Diagnostics:', 1, true) ~= nil

  -- Read file line by line to safely track layout sections
  for line in string.gmatch(file_content, '[^\r\n]+') do
    local clean_line = vim.trim(line)

    if clean_line == '# Dynamic configuration block generated by nvim-pio' then
      in_dynamic_block = true
    end

    table.insert(output_lines, line)

    -- Inject dynamic flags directly inside CompileFlags.Remove array boundary
    if in_dynamic_block and clean_line == 'CompileFlags:' then
      -- Next line will be our target Remove slot
    elseif in_dynamic_block and clean_line == 'Remove: [' then
      in_remove_array = true
      for flag, _ in pairs(flags_to_add) do
        table.insert(output_lines, '    "' .. flag .. '",')
      end
    end
  end

  -- 3. Append warning codes neatly under a single block configuration
  if has_diagnostics_block and in_dynamic_block then
    -- Inject warnings directly into the pre-existing block array
    local updated_lines = {}
    local in_dynamic_diag = false
    for _, l in ipairs(output_lines) do
      local cl = vim.trim(l)
      if cl == '# Dynamic configuration block generated by nvim-pio' then
        in_dynamic_diag = true
      end
      table.insert(updated_lines, l)
      if in_dynamic_diag and cl == 'Suppress: [' then
        for code, _ in pairs(codes_to_add) do
          table.insert(updated_lines, '    ' .. code .. ',')
        end
      end
    end
    output_lines = updated_lines
  else
    -- If no diagnostic section exists yet in the lower block, create a clean one at the bottom
    local first_code = true
    for code, _ in pairs(codes_to_add) do
      if first_code then
        table.insert(output_lines, '\nDiagnostics:\n  Suppress: [')
        first_code = false
      end
      table.insert(output_lines, '    ' .. code .. ',')
    end
    if not first_code then
      table.insert(output_lines, '  ]')
    end
  end

  -- Commit perfectly formatted document back to disk with standard Unix newlines
  local f_write = io.open(local_clangd_file, 'wb')
  if f_write then
    f_write:write(table.concat(output_lines, '\n') .. '\n')
    f_write:close()
    return true
  end

  return false
end

-- ====================================================================
-- 3. THE GROUPED INTERACTIVE SELECTION ENGINE
-- ====================================================================
function M.manage_file_diagnostics_interactive()
  local current_buf = vim.api.nvim_get_current_buf()
  local diagnostics = vim.diagnostic.get(current_buf)

  if #diagnostics == 0 then
    vim.notify('✅ No active LSP diagnostics found in this file!', vim.log.levels.INFO)
    return
  end

  local groups = {}
  local group_names = {}

  for _, diag in ipairs(diagnostics) do
    local group_key = diag.code or 'uncategorized_noise'
    if not groups[group_key] then
      groups[group_key] = {}
      table.insert(group_names, group_key)
    end
    table.insert(groups[group_key], diag)
  end

  vim.ui.select(group_names, {
    prompt = ' 📂 Select an Error Group Type to Manage ',
    format_item = function(code)
      return string.format('Group [%s] — (%d active instances found)', code, #groups[code])
    end,
  }, function(selected_group)
    if not selected_group then
      return
    end

    local group_diagnostics = groups[selected_group]
    local options = {
      '💥 Suppress ALL errors inside group [' .. selected_group .. ']',
      '🔍 Inspect and pick specific instances one by one',
    }

    vim.ui.select(options, {
      prompt = ' Action for group [' .. selected_group .. '] ',
    }, function(action_choice)
      if not action_choice then
        return
      end

      -- 🌟 ROBUST STRING EVALUATION
      if action_choice:find('💥 Suppress ALL') then
        local batch_items = {}
        for _, diag in ipairs(group_diagnostics) do
          table.insert(batch_items, {
            code = diag.code or selected_group,
            message = diag.message,
          })
        end

        if inject_batch_into_clangd(batch_items) then
          vim.notify('✅ Bulk action complete! Added all new suppressions to .clangd', vim.log.levels.WARN, { title = 'Project .clangd Mangler' })
          require('nvimpio.clangd.control').restart()
        else
          vim.notify('ℹ All items in group are already fully suppressed.', vim.log.levels.INFO)
        end
      else
        local individual_items = {}
        for _, diag in ipairs(group_diagnostics) do
          table.insert(individual_items, {
            code = diag.code or selected_group,
            message = diag.message,
            line = diag.lnum + 1,
          })
        end

        vim.ui.select(individual_items, {
          prompt = ' 🛠 Select exact single instance line item to ignore ',
          format_item = function(item)
            return string.format('Line %d: %s', item.line, item.message:sub(1, 65) .. '...')
          end,
        }, function(final_choice)
          if not final_choice then
            return
          end

          if inject_batch_into_clangd({ final_choice }) then
            local is_driver = string.match(tostring(final_choice.code):lower(), '^drv_') or string.match(final_choice.message:lower(), 'unknown argument')
            local msg = is_driver and 'Stripped matching toolchain argument!' or 'Suppressed diagnostic code globally!'
            vim.notify('✅ ' .. msg, vim.log.levels.WARN, { title = 'Project .clangd Mangler' })
            require('nvimpio.clangd.control').restart()
          else
            vim.notify('ℹ Item is already handled inside configuration profiles.', vim.log.levels.INFO)
          end
        end)
      end
    end)
  end)
end

return M
