local M = {}

---@meta
---@diagnostic disable: undefined-global

local local_clangd_file = vim.fn.getcwd() .. '/.clangd'

--- Formats a completely empty skeleton baseline template if .clangd is missing
local function ensure_baseline_template()
  local f_check = io.open(local_clangd_file, 'r')
  if not f_check then
    local f_init = io.open(local_clangd_file, 'wb')
    if f_init then
      -- Both baseline and dynamic blocks initialized as pristine, empty YAML arrays
      local baseline_template = [[
CompileFlags:
  Remove: []
  Add: []
Diagnostics:
  Suppress: []

---
# Dynamic configuration block generated by nvim-pio
CompileFlags:
  Remove: []
Diagnostics:
  Suppress: []
]]
      f_init:write(baseline_template)
      f_init:close()
    end
  else
    f_check:close()
  end
end

--- Force-kills and re-spawns active compiler processes ONLY for clangd buffers
function M.restart()
  vim.schedule(function()
    -- Loop over loaded buffers and surgically clear diagnostics ONLY if clangd is attached
    for _, bufnr in ipairs(vim.api.nvim_list_bufs()) do
      if vim.api.nvim_buf_is_loaded(bufnr) then
        local active_clients = vim.lsp.get_clients({ bufnr = bufnr, name = 'clangd' })
        if #active_clients > 0 then
          vim.diagnostic.reset(nil, bufnr)
        end
      end
    end
    -- Force Neovim to tear down and reload clangd client instances
    -- vim.cmd('LspRestart clangd')
    require('nvimpio.clangd.control').restart()
  end)
end

--- Parses and writes data directly into the active dynamic block scope arrays
local function inject_into_clangd(code, message)
  ensure_baseline_template()

  local file_content = ''
  local f_read = io.open(local_clangd_file, 'rb')
  if f_read then
    file_content = f_read:read('*all')
    f_read:close()
  end

  local target_item = tostring(code or '')
  local is_driver_flag = string.match(target_item:lower(), '^drv_') or string.match(message:lower(), 'unknown argument')

  if is_driver_flag then
    local extracted_flag = string.match(message, '[\'"](%-.-)[\'"]') or string.match(message, '%s(%-.*)%s')
    if not extracted_flag then
      extracted_flag = string.match(message, 'argument%s+(%-.*)$') or '-mlongcalls'
    end
    target_item = vim.trim(extracted_flag):gsub('[\',;"%s]', '')
  else
    if target_item == '' or target_item:match('^table:') or target_item == 'uncategorized_noise' then
      target_item = message:match('%[(.-)%]') or message:match("'(.-)'") or 'uncategorized_noise'
    end
    target_item = vim.trim(target_item):gsub('[\',;"%s]', '')
  end

  local divider = '# Dynamic configuration block generated by nvim-pio'
  local sections = vim.split(file_content, divider, { plain = true })

  local base_part = tostring(sections[1] or '')
  local dynamic_part = tostring(sections[2] or '')
  dynamic_part = dynamic_part:gsub('\r', '')

  -- Prevent structural entry duplicates from leaking into arrays
  if string.find(dynamic_part, '"' .. target_item .. '"', 1, true) then
    return false
  end

  local clean_dynamic = dynamic_part
  local replacements_made = 0

  if is_driver_flag then
    local pattern = '([Cc]ompile[Ff]lags:%s*\n%s*[Rr]emove:%s*%[%s*\n?)'
    local replacement = 'CompileFlags:\n  Remove: [\n    "' .. target_item .. '",\n'
    clean_dynamic, replacements_made = string.gsub(clean_dynamic, pattern, replacement, 1)
  else
    local pattern = '([Dd]iagnostics:%s*\n%s*[Ss]uppress:%s*%[%s*\n?)'
    local replacement = 'Diagnostics:\n  Suppress: [\n    "' .. target_item .. '",\n'
    clean_dynamic, replacements_made = string.gsub(clean_dynamic, pattern, replacement, 1)
  end

  -- Safe structural fallback routine if formatting brackets are collapsed
  if replacements_made == 0 then
    if is_driver_flag then
      clean_dynamic = clean_dynamic .. '\nCompileFlags:\n  Remove: [\n    "' .. target_item .. '"\n  ]'
    else
      clean_dynamic = clean_dynamic .. '\nDiagnostics:\n  Suppress: [\n    "' .. target_item .. '"\n  ]'
    end
  end

  local final_content = base_part .. divider .. clean_dynamic
  local f_write = io.open(local_clangd_file, 'wb')
  if f_write then
    f_write:write(final_content)
    f_write:close()
  end

  return true
end

--- Interactive UI dashboard runner component utilizing native select loops
function M.manage_file_diagnostics_interactive()
  local current_buf = vim.api.nvim_get_current_buf()
  local diagnostics = vim.diagnostic.get(current_buf)

  if #diagnostics == 0 then
    vim.notify('✅ Complete Parity: No active compiler exceptions detected!', vim.log.levels.INFO)
    return
  end

  -- Filter duplicates to keep UI selections clear
  local unique_items = {}
  local seen_keys = {}

  for _, diag in ipairs(diagnostics) do
    local raw_code = diag.code
    local code_name = ''

    -- Lint-safe explicit conditional check to completely satisfy lua-ls rules
    if type(raw_code) == 'table' then
      code_name = tostring(raw_code.code or 'uncategorized_noise')
    else
      code_name = tostring(raw_code or 'uncategorized_noise')
    end

    local unique_key = code_name .. '::' .. diag.message
    if not seen_keys[unique_key] then
      seen_keys[unique_key] = true
      table.insert(unique_items, {
        code = code_name,
        message = diag.message,
        line = diag.lnum + 1,
      })
    end
  end

  -- Triggers your dropdown popup view via unified core selector mappings
  vim.ui.select(unique_items, {
    prompt = '🔍 Microcontroller Diagnostic Mangler',
    format_item = function(item)
      return string.format('[%s] (Line %d) -> %s', item.code, item.line, item.message)
    end,
  }, function(choice)
    if not choice then
      return
    end

    local success = inject_into_clangd(choice.code, choice.message)

    -- Force Surgical Cache Clear Pipeline
    vim.schedule(function()
      M.restart()
      vim.cmd('edit!')
    end)

    if success then
      vim.notify('🔒 Suppression Committed: Injected [' .. choice.code .. '] into .clangd', vim.log.levels.WARN, { title = 'Compiler Mangler' })
    else
      vim.notify('ℹ️ Item is already successfully mapped inside .clangd', vim.log.levels.INFO)
    end
  end)
end

return M
