local M = {}

---@meta
---@diagnostic disable: undefined-global

local local_clangd_file = vim.fn.getcwd() .. '/.clangd'

local function print_telemetry(phase, data)
  vim.schedule(function()
    vim.api.nvim_echo({
      { '🔍 [TELEMETRY: ' .. phase .. ']\n', 'DiagnosticHint' },
      { vim.inspect(data) .. '\n', 'Normal' },
    }, true, {})
  end)
end

local function ensure_baseline_template()
  local f_check = io.open(local_clangd_file, 'r')
  if not f_check then
    local f_init = io.open(local_clangd_file, 'wb')
    if f_init then
      local baseline_template = [[
CompileFlags:
  Remove: []
  Add:
    [
      "-xc++",
      "-std=gnu++17",
      "-Wno-unknown-argument",
      "-Wno-macro-redefined",
      "-Wno-invalid-token-paste",
      "-Wno-typedef-redefinition",
      "-Wno-unknown-attributes",
      "-Wno-pragma-system-header-outside-header",
      "-Wno-unknown-warning-option",
      "-Wno-unused-includes",
    ]
Diagnostics:
  Suppress:
    [
      "macro_too_many_args",
      "unused_macro_definition",
      "pp_file_not_found",
      "pp_file_not_found_angled_not_fatal",
      "pp_included_file_not_found",
      "pp_including_mainfile_in_preamble",
      "unused-includes",
      "misc-definitions-in-headers",
    ]
  ClangTidy:
    Remove: ["readability-*", "modernize-*", "bugprone-*", "cert-err58-cpp"]

---
# Dynamic configuration block generated by nvim-pio
CompileFlags:
  Remove: [
    "-mlongcalls",
    "-fstrict-volatile-bitfields",
    "-fno-tree-switch-conversion"
  ]
Diagnostics:
  Suppress: [
    "uncategorized_noise"
  ]
]]
      f_init:write(baseline_template)
      f_init:close()
    end
  else
    f_check:close()
  end
end

local function inject_into_clangd(code, message)
  ensure_baseline_template()

  local file_content = ''
  local f_read = io.open(local_clangd_file, 'rb')
  if f_read then
    file_content = f_read:read('*all')
    f_read:close()
  end

  local target_item = tostring(code or '')
  local is_driver_flag = string.match(target_item:lower(), '^drv_') or string.match(message:lower(), 'unknown argument')

  if is_driver_flag then
    local extracted_flag = string.match(message, '[\'"](%-.-)[\'"]') or string.match(message, '%s(%-.-)%s')
    if not extracted_flag then
      extracted_flag = string.match(message, 'argument%s+(%-.*)$') or '-mlongcalls'
    end
    target_item = vim.trim(extracted_flag):gsub('[\',;"%s]', '')
  else
    if target_item == '' or target_item:match('^table:') or target_item == 'uncategorized_noise' then
      target_item = message:match('%[(.-)%]') or message:match("'(.-)'") or 'uncategorized_noise'
    end
    target_item = vim.trim(target_item):gsub('[\',;"%s]', '')
  end

  local divider = '# Dynamic configuration block generated by nvim-pio'
  local sections = vim.split(file_content, divider, { plain = true })
  local base_part = tostring(sections[1] or '')
  local dynamic_part = tostring(sections[2] or '')

  dynamic_part = dynamic_part:gsub('\r', '')

  if string.find(dynamic_part, '"' .. target_item .. '"', 1, true) then
    return false
  end

  local clean_dynamic = dynamic_part
  local replacements_made = 0

  if is_driver_flag then
    local pattern = '([Cc]ompile[Ff]lags:%s*\n%s*[Rr]emove:%s*%[%s*\n)'
    local replacement = 'CompileFlags:\n  Remove: [\n    "' .. target_item .. '",\n'
    clean_dynamic, replacements_made = string.gsub(clean_dynamic, pattern, replacement, 1)
  else
    local pattern = '([Dd]iagnostics:%s*\n%s*[Ss]uppress:%s*%[%s*\n)'
    local replacement = 'Diagnostics:\n  Suppress: [\n    "' .. target_item .. '",\n'
    clean_dynamic, replacements_made = string.gsub(clean_dynamic, pattern, replacement, 1)
  end

  if replacements_made == 0 then
    if is_driver_flag then
      clean_dynamic = clean_dynamic .. '\nCompileFlags:\n  Remove: [\n    "' .. target_item .. '"\n  ]'
    else
      clean_dynamic = clean_dynamic .. '\nDiagnostics:\n  Suppress: [\n    "' .. target_item .. '"\n  ]'
    end
  end

  local final_content = base_part .. divider .. clean_dynamic
  local f_write = io.open(local_clangd_file, 'wb')
  if f_write then
    f_write:write(final_content)
    f_write:close()
  end

  return true
end

function M.manage_file_diagnostics_interactive()
  if not pcall(require, 'snacks') then
    return
  end

  local current_buf = vim.api.nvim_get_current_buf()
  local diagnostics = vim.diagnostic.get(current_buf)

  if #diagnostics == 0 then
    vim.notify('✅ No active diagnostics detected!', vim.log.levels.INFO)
    return
  end

  local picker_items = {}
  for _, diag in ipairs(diagnostics) do
    local code_name = diag.code
    if type(code_name) == 'table' then
      code_name = code_name.code or code_name
    end
    code_name = tostring(code_name or 'uncategorized_noise')

    table.insert(picker_items, {
      text = string.format('[%s] Line %d', code_name, diag.lnum + 1),
      comment = diag.message,
      idx = #picker_items + 1,
      code = code_name,
      message = diag.message,
      icon = '❌',
    })
  end

  -- ====================================================================
  -- CORE TELEMETRY CONFIGURATION METHOD
  -- ====================================================================
  Snacks.picker({
    source = 'Microcontroller Diagnostic Mangler',
    items = picker_items,
    layout = 'vscode',

    -- Explicitly notify the core engine that the stream is local and non-blocking
    live = false,

    -- BIND ACTIONS USING NATIVE PROPERTY INJECTION DEFINITIONS
    confirm = function(picker)
      local current = picker:current()
      print_telemetry('CONFIRM ACTION FIRED', { current_row = current })

      picker:close()
      if not current then
        return
      end

      local success = inject_into_clangd(current.code, current.message)
      print_telemetry('FILE WRITE STATUS', { success = success })

      vim.schedule(function()
        vim.diagnostic.reset(nil, current_buf)
        pcall(function()
          require('nvimpio.clangd.control').restart()
        end)
        vim.cmd('edit!')
      end)
    end,

    -- FORCE KEYBIND ASSIGNMENT AT THE ROOT LEVEL VIA DELEGATED INJECTION
    win = {
      input = {
        keys = {
          -- We block Enter completely from evaluating structural lookup functions
          ['<Cr>'] = { 'confirm', mode = { 'n', 'i' } },
        },
      },
    },
  })
end

return M
