local M = {}
-- ====================================================================
-- HELPERS FOR STRUCTURAL FILE INJECTION
-- ====================================================================
local function get_local_clangd_path()
  local current_buf = vim.api.nvim_get_current_buf()
  local current_file = vim.api.nvim_buf_get_name(current_buf)

  -- Search upward for PlatformIO or Git markers to locate the project root
  local root_markers = { 'platformio.ini', '.git', '.clangd' }
  local root_dir = vim.fs.root(current_file, root_markers) or vim.fn.getcwd()

  return root_dir .. '/.clangd'
end

local function ensure_baseline_template()
  local local_clangd_file = get_local_clangd_path()
  local f_check = io.open(local_clangd_file, 'r')
  if not f_check then
    local f_init = io.open(local_clangd_file, 'wb')
    if f_init then
      local baseline_template = [[
CompileFlags:
  Remove: []
  Add:
    [
      "-xc++",
      "-std=gnu++17",
      "-Wno-unknown-argument",
      "-Wno-macro-redefined",
      "-Wno-invalid-token-paste",
      "-Wno-typedef-redefinition",
      "-Wno-unknown-attributes",
      "-Wno-pragma-system-header-outside-header",
      "-Wno-unknown-warning-option",
      "-Wno-unused-includes",
    ]
Diagnostics:
  Suppress:
    [
      "macro_too_many_args",
      "unused_macro_definition",
      "pp_file_not_found",
      "pp_file_not_found_angled_not_fatal",
      "pp_included_file_not_found",
      "pp_including_mainfile_in_preamble",
      "unused-includes",
      "misc-definitions-in-headers",
    ]
  ClangTidy:
    Remove: ["readability-*", "modernize-*", "bugprone-*", "cert-err58-cpp"]

---
# Dynamic configuration block generated by nvim-pio
CompileFlags:
  Remove: [
    "-mlongcalls",
    "-fstrict-volatile-bitfields",
    "-fno-tree-switch-conversion"
    ]
]]
      f_init:write(baseline_template)
      f_init:close()
    end
  else
    f_check:close()
  end
end

local function inject_batch_into_clangd(items_list)
  ensure_baseline_template()
  local local_clangd_file = get_local_clangd_path()

  local file_content = ''
  local f_read = io.open(local_clangd_file, 'rb')
  if f_read then
    file_content = f_read:read('*all')
    f_read:close()
  end

  local sep_marker = '# Dynamic configuration block generated by nvim-pio'
  local sections = vim.split(file_content, sep_marker, { plain = true })
  local base_part = sections[1] or ''
  local dynamic_part = sections[2] or ''

  local added_count = 0
  local flags_to_add = {}
  local codes_to_add = {}

  for _, item in ipairs(items_list) do
    local target_item = ''
    local is_driver_flag = string.match(tostring(item.code):lower(), '^drv_')
      or string.match(item.message:lower(), 'unknown argument')
      or string.match(item.message:lower(), '%-mlongcalls')

    if is_driver_flag then
      local extracted_flag = string.match(item.message, '[\'"](%-.-)[\'"]') or string.match(item.message, '%s(%-.*)%s')
      if not extracted_flag then
        extracted_flag = string.match(item.message, 'argument%s+(%-.*)$') or '-mlongcalls'
      end
      target_item = vim.trim(extracted_flag):gsub('[\',;"%s]', '')

      local search_signature = '"' .. target_item .. '"'
      if not string.find(file_content, search_signature, 1, true) then
        flags_to_add[target_item] = true
      end
    else
      target_item = item.code
      if target_item and target_item ~= '' and target_item ~= 'uncategorized_noise' then
        if not string.find(file_content, target_item, 1, true) then
          codes_to_add[target_item] = true
        end
      end
    end
  end

  local updated_dynamic = dynamic_part

  for flag, _ in pairs(flags_to_add) do
    local pattern = '(CompileFlags:%s*\n%s*Remove:%s*%[)'
    local replacement = 'CompileFlags:\n  Remove: [\n    "' .. flag .. '",'
    updated_dynamic = string.gsub(updated_dynamic, pattern, replacement)
    added_count = added_count + 1
  end

  for code, _ in pairs(codes_to_add) do
    if string.find(updated_dynamic, 'Diagnostics:%s*\n%s*Suppress:%s*%[') then
      local pattern = '(Diagnostics:%s*\n%s*Suppress:%s*%[)'
      local replacement = 'Diagnostics:\n  Suppress: [\n    ' .. code .. ','
      updated_dynamic = string.gsub(updated_dynamic, pattern, replacement)
    else
      updated_dynamic = updated_dynamic .. '\n\nDiagnostics:\n  Suppress: [\n    ' .. code .. ',\n  ]'
    end
    added_count = added_count + 1
  end

  if added_count > 0 then
    local final_content = base_part .. sep_marker .. updated_dynamic
    local f_write = io.open(local_clangd_file, 'wb')
    if f_write then
      f_write:write(final_content)
      f_write:close()
    end
    return true
  end

  return false
end

-- ====================================================================
-- 3. THE GROUPED INTERACTIVE SELECTION ENGINE
-- ====================================================================
function M.manage_file_diagnostics_interactive()
  local current_buf = vim.api.nvim_get_current_buf()
  local diagnostics = vim.diagnostic.get(current_buf)

  if #diagnostics == 0 then
    vim.notify('✅ No active LSP diagnostics found in this file!', vim.log.levels.INFO)
    return
  end

  local groups = {}
  local group_names = {}

  for _, diag in ipairs(diagnostics) do
    local group_key = diag.code or 'uncategorized_noise'
    if not groups[group_key] then
      groups[group_key] = {}
      table.insert(group_names, group_key)
    end
    table.insert(groups[group_key], diag)
  end

  vim.ui.select(group_names, {
    prompt = ' 📂 Select an Error Group Type to Manage ',
    format_item = function(code)
      return string.format('Group [%s] — (%d active instances found)', code, #groups[code])
    end,
  }, function(selected_group)
    if not selected_group then
      return
    end

    local group_diagnostics = groups[selected_group]
    local options = {
      '💥 Suppress ALL errors inside group [' .. selected_group .. ']',
      '🔍 Inspect and pick specific instances one by one',
    }

    vim.ui.select(options, {
      prompt = ' Action for group [' .. selected_group .. '] ',
    }, function(action_choice)
      if not action_choice then
        return
      end

      -- 🌟 FIXED CRITICAL CONDITION TRACKING: Check array index index 1 directly
      if action_choice == options[1] then
        local batch_items = {}
        for _, diag in ipairs(group_diagnostics) do
          table.insert(batch_items, {
            code = diag.code or selected_group,
            message = diag.message,
          })
        end

        if inject_batch_into_clangd(batch_items) then
          vim.notify('✅ Bulk action complete! Added all new suppressions to .clangd', vim.log.levels.WARN, { title = 'Project .clangd Mangler' })
          require('nvimpio.clangd.control').restart()
        else
          vim.notify('ℹ All items in group are already fully suppressed.', vim.log.levels.INFO)
        end
      else
        local individual_items = {}
        for _, diag in ipairs(group_diagnostics) do
          table.insert(individual_items, {
            code = diag.code or selected_group,
            message = diag.message,
            line = diag.lnum + 1,
          })
        end

        vim.ui.select(individual_items, {
          prompt = ' 🛠 Select exact single instance line item to ignore ',
          format_item = function(item)
            return string.format('Line %d: %s', item.line, item.message:sub(1, 65) .. '...')
          end,
        }, function(final_choice)
          if not final_choice then
            return
          end

          if inject_batch_into_clangd({ final_choice }) then
            local is_driver = string.match(tostring(final_choice.code):lower(), '^drv_') or string.match(final_choice.message:lower(), 'unknown argument')
            local msg = is_driver and 'Stripped matching toolchain argument!' or 'Suppressed diagnostic code globally!'
            vim.notify('✅ ' .. msg, vim.log.levels.WARN, { title = 'Project .clangd Mangler' })
            require('nvimpio.clangd.control').restart()
          else
            vim.notify('ℹ Item is already handled inside configuration profiles.', vim.log.levels.INFO)
          end
        end)
      end
    end)
  end)
end

return M
